### ISSUE TITLE
TypeError: mqtt.createClient is not a function

### ISSUE THREAD

**Issue by rbswift** [the1laz/cgateweb#30]
I'm getting the following exception when I first try to start cgateweb. Any help greatly appreciated!

```
pi@pi4:/usr/local/bin/cgateweb $ /usr/bin/nodejs /usr/local/bin/cgateweb/index.js
/usr/local/bin/cgateweb/index.js:37
var client = mqtt.createClient(mqtt_url.port, mqtt_url.hostname,OPTIONS);
                  ^

TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/usr/local/bin/cgateweb/index.js:37:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

```

**Comment by CraigD80** [comment]
Just been through this myself a few days ago. The problem is mqtt,createClient is no longer supported in recent versions of nodejs. For example I installed version 18 and got the same error. You have two options, install an older version of nodejs (you will have to go to their website and look at the documention to see what was the last version supporting this, or modify the file index.js on your machine.
Replace the line with:
`var client = mqtt.connect(mqtt_url,mqttOptions);`

And add the following as well to pick up you mqtt brokers user name and password which you have defined in settings.js
`
const mqttOptions={
clientId:'mqtt-cgate',
username: settings.mqttusername,
password: settings.mqttpassword,
clean:true};
`
Where in my case 'mqtt-cgate' is the name of the machine I have installed cgate on, so substitue your machines name there.
Good luck!

**Comment by rbswift** [comment]
That's awesome thanks @CraigD80

If I can get it working I might try to add a PR

**Comment by the1laz** [comment]
Thanks, I'll have a look this week. Sorry for the delay replying.

**Comment by bdnstn** [comment]
Hi Steven,

I've just (past few minutes) progressed past that point. Rbswift has created a fork with many changes and I'm past that particular issue, and on to another one now.

Thanks,
Brian
